### ISSUE TITLE
user-can-access-drinks-or-food-search

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to toggle between APIs and app schemes for searching recipes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will start on the "Meals" side and will be able to search for food recipes.
They can hit the "Drinks" button and then will be able to search for drink recipes.
When in the "Drinks" screen, they can hit the "Meals" button to return to the starting page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Component 2](https://user-images.githubusercontent.com/82407007/121298309-7fda3580-c8a8-11eb-861b-a190df70a782.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create all the CSS required to make the application
- [x] Make “Drinks” & “Meals” buttons
- [x] Make these buttons “toggleable” to switch between color and API
- [x] Add listener to search bar for input
- [x] String together requests for Area, Name, Main Ingredient
- [x] Create an array of results and keep only unique results
- [x] Create DOM object to inset for each result
- [x] Test in private browser
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by CristoferMar** [comment]
![CookItUp_Feature_1](https://user-images.githubusercontent.com/82407007/121817439-57e72b00-cc36-11eb-9d4f-253dac3cbc32.gif)
