### ISSUE TITLE
Issue 5 User can view their “Loved” & “Bookmarked” lists

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/ajax-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The User will be able to navigate to the Loved and Bookmarked pages, to view ether list's recipe thumbs

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks on the "Loved" navigation buttons, they will see the recipe thumbs of all recipes they have loved.
If the user clicks on the "Bookmarked" navigation buttons, they will see the recipe thumbs of all recipes they have bookmarked.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CootItUp Loved Page](https://user-images.githubusercontent.com/82407007/122620226-3ecfe700-d047-11eb-9fb8-b46032482659.png)
![CootItUp BookMarked Page](https://user-images.githubusercontent.com/82407007/122620231-41cad780-d047-11eb-84db-0c80f36735b7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add event listeners for the navigation buttons
- [x] check to make sure the user is not already on this page.
- [x] If they go to a different page, swap views
- [x] When **page first loads** GET request to create new thumbs for their loved and bookmarked galleries
- [x] Add rules to add thumbs to loved or bookmarked galleries when corresponding icons are clicked
- [x] Add rules to remove them if the icons are unclicked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by CristoferMar** [comment]
![CookItUp_Feature_5](https://user-images.githubusercontent.com/82407007/122620090-e7317b80-d046-11eb-8efd-f345f75d6732.gif)
