### ISSUE TITLE
Issue-2-user-can-search-random-recipes

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Hitting the randomizer button will generate 6 random recipe thumbs, for the user to browse.
These 6 thumbs will replace the last searched items, by the user.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The random icon will be clicked. 6 entirely random recipe thumbs will appear on the screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an IF condition to the navbar event listener
- [x] Unlike the search form, If the random button is hit, clear the searched the HTML and DATA manually
- [x] Run the search in a FOR loop, for 6 searched in total.
- [x] Add search counter of 6 to search function, to trigger the posting function.
- [x] If random is clicked, reset search bar
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by CristoferMar** [comment]
![CookItUp_Feature_2](https://user-images.githubusercontent.com/82407007/122117203-6de22080-cddb-11eb-8580-74d392973ca8.gif)
