### ISSUE TITLE
Issue 6 User can view a whole recipe

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a whole recipe

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click on a recipe thumb.
Once they click on it, the search bar and all recipe thumbs will be replaced with one page for the recipe.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CootItUp whole recipe](https://user-images.githubusercontent.com/82407007/122128092-04690e80-cde9-11eb-8bcb-0a40b947ac27.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the styling for the recipe page onto the current application's recipe section
- [x] Add event listener for recipe-thumbs, click
- [x] Clear content of current/previous recipe, when a recipe-thumb is clicked
- [x] When a recipe is clicked, send a GET request to retrieve the entire recipe & append it to data.currentRecipe
- [x] Add functionality to view swapper to update the title of the page, to the recipe title
- [x] Append an ingredients list to the recipe page's ingredients section
- [x] Append preparation steps to the page
- [x] If heart or bookmark icons are clicked, generate recipe thumb and add it to the appropriate list
- [x] Update heart or bookmark icon on each existing thumb.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
