### ISSUE TITLE
Issue 3 User can save recipes to "Bookemarked" list

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can save and view their bookmarks.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks on the bookmarks icon, the icon will change to a solid-filled bookmark icon.
Should they clikc a filled bookmark, it will be unselected and the recipe will be removed from their bookmark
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CootItUp BookMarked Page](https://user-images.githubusercontent.com/82407007/122274677-ac3d1580-ce97-11eb-9ad3-c08004077dfb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listener to body for click on bookmark icon
- [x] Get ID from entire container
- [x] Add ID to appropriate bookmarked array
- [x] Replace bookmark image with filled bookmark.
- [x] If user clicks an already bookmarked tumb, remove bookmark
- [x] Remove the ID of selected item from appropriate bookmarked array
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by CristoferMar** [comment]
![CookItUp_Feature_3](https://user-images.githubusercontent.com/82407007/122142229-dcd36f80-ce03-11eb-9d29-63446033c4c1.gif)
