### ISSUE TITLE
Issue 4 User can save recipes to "Loved" list

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/ajax-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can save and view their "Loved" recipes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks on the Heart icon, the icon will change to a solid-filled Heart icon.
Should they click a filled Heart, it will be unselected and the recipe will be removed from their Loved list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CootItUp Loved Page](https://user-images.githubusercontent.com/82407007/122274814-d989c380-ce97-11eb-9e34-8a6f48668312.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Add event listener to the gallery for click on the heart icon
- [x] Get ID from entire container
- [x] Add ID to appropriate Loved array
- [x] Replace heart image with filled heart.
- [x] If the user clicks an already loved tumb, remove Loved 
- [x] Remove the ID of the selected item from the appropriate Loved array
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by CristoferMar** [comment]
![CookItUp_Feature_4](https://user-images.githubusercontent.com/82407007/122282710-93852d80-cea0-11eb-864a-f6f725b8df02.gif)
